import React, { useState, useEffect } from 'react';
import { apiRequest } from '../../../services/api';
import { ScientificChat } from '../components/ScientificChat';
import { ReactFlow, Background, Controls, MiniMap } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import _createPlotlyComponent from 'react-plotly.js/factory';
import Plotly from 'plotly.js-dist-min';

const createPlotlyComponent = typeof _createPlotlyComponent === 'function'
  ? _createPlotlyComponent
  : (_createPlotlyComponent as any).default;

const Plot = createPlotlyComponent(Plotly);
import { 
  Sparkles, 
  Terminal, 
  Layout, 
  Compass, 
  PlusCircle, 
  Calendar,
  CheckSquare
} from 'lucide-react';

interface Session {
  id: number;
  title: string;
  created_at: string;
}

export const CopilotDashboard: React.FC = () => {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<number | null>(null);
  
  // Tab control for results display
  const [activeResultTab, setActiveResultTab] = useState<'plan' | 'dashboard' | 'workflow'>('plan');

  // Widget states generated by Copilot
  const [activeQueryPlan, setActiveQueryPlan] = useState<any | null>(null);
  const [activeDashboard, setActiveDashboard] = useState<any | null>(null);
  const [activeWorkflow, setActiveWorkflow] = useState<any | null>(null);

  useEffect(() => {
    loadSessions();
  }, []);

  const loadSessions = async () => {
    try {
      const data = await apiRequest('/copilot/chat/sessions', { service: 'ai' });
      setSessions(data);
      if (data.length > 0 && !activeSessionId) {
        setActiveSessionId(data[0].id);
      }
    } catch (err) {
      console.error('Failed to load sessions:', err);
    }
  };

  const startNewSession = () => {
    setActiveSessionId(null);
    // Reset widget states
    setActiveQueryPlan(null);
    setActiveDashboard(null);
    setActiveWorkflow(null);
  };

  const handleSessionCreated = (id: number) => {
    setActiveSessionId(id);
    loadSessions();
  };

  const handleWidgetGenerated = (type: 'query' | 'dashboard' | 'workflow', data: any) => {
    if (type === 'query') {
      setActiveQueryPlan(data);
      setActiveResultTab('plan');
    } else if (type === 'dashboard') {
      setActiveDashboard(data);
      setActiveResultTab('dashboard');
    } else if (type === 'workflow') {
      // Map nodes and edges for React Flow representation
      const nodes = (data.nodes || []).map((n: any, idx: number) => ({
        id: n.id,
        type: n.type === 'approval' || n.type === 'notification' ? 'default' : 'input',
        position: n.position || { x: 100 + idx * 180, y: 150 },
        data: { label: n.data?.label || n.type },
        style: {
          background: n.type === 'approval' ? '#7f1d1d' : n.type === 'notification' ? '#581c87' : '#0f172a',
          color: '#f8fafc',
          border: '1px solid #38bdf8',
          borderRadius: '8px',
          fontSize: '11px',
          fontWeight: '600'
        }
      }));

      const edges = (data.edges || []).map((e: any) => ({
        id: e.id,
        source: e.source,
        target: e.target,
        animated: true,
        style: { stroke: '#38bdf8' }
      }));

      setActiveWorkflow({
        ...data,
        flowNodes: nodes,
        flowEdges: edges
      });
      setActiveResultTab('workflow');
    }
  };

  const handleSaveWorkflow = async () => {
    if (!activeWorkflow) return;
    try {
      // Post workflow to actual workflow service on port 8009
      const payload = {
        name: activeWorkflow.name,
        description: activeWorkflow.description,
        nodes_json: JSON.stringify(activeWorkflow.nodes),
        edges_json: JSON.stringify(activeWorkflow.edges),
        trigger_type: activeWorkflow.trigger_type,
        cron_schedule: activeWorkflow.cron_schedule,
        is_active: true
      };
      
      const res = await apiRequest('/workflows', {
        service: 'workflow',
        method: 'POST',
        body: JSON.stringify(payload)
      });
      
      alert(`Workflow "${res.name}" successfully compiled and registered!`);
    } catch (err: any) {
      console.error('Failed to save workflow:', err);
      alert(`Failed to register workflow: ${err.message || err}`);
    }
  };

  return (
    <div className="flex h-full bg-[#080d19] text-slate-100 overflow-hidden">
      {/* Sessions Sidebar */}
      <aside className="w-64 bg-[#0b1121] border-r border-[#1e293b] flex flex-col justify-between hidden md:flex">
        <div className="p-4 flex flex-col h-full space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Conversations</h3>
            <button
              onClick={startNewSession}
              className="p-1 rounded bg-sky-500/10 hover:bg-sky-500/20 text-sky-400 border border-sky-500/30 transition-all"
              title="Start New Discussion"
            >
              <PlusCircle className="h-4 w-4" />
            </button>
          </div>

          <div className="flex-1 overflow-y-auto space-y-1.5 pr-1">
            {sessions.map((sess) => (
              <button
                key={sess.id}
                onClick={() => setActiveSessionId(sess.id)}
                className={`w-full text-left px-3 py-2.5 rounded-lg text-xs transition-all flex flex-col space-y-1 border ${
                  activeSessionId === sess.id
                    ? 'bg-sky-500/10 border-sky-500/30 text-sky-400 font-semibold'
                    : 'bg-[#101729] border-transparent text-slate-400 hover:bg-[#131d35] hover:text-slate-200'
                }`}
              >
                <span className="truncate">{sess.title}</span>
                <span className="text-[9px] text-slate-500 flex items-center">
                  <Calendar className="h-3 w-3 mr-1" />
                  {new Date(sess.created_at).toLocaleDateString()}
                </span>
              </button>
            ))}
          </div>
        </div>
      </aside>

      {/* Main Workspace */}
      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden p-4 gap-4">
        {/* Chat Panel */}
        <div className="w-full lg:w-[420px] xl:w-[460px] h-full flex flex-col shrink-0">
          <ScientificChat
            sessionId={activeSessionId}
            onSessionCreated={handleSessionCreated}
            onWidgetGenerated={handleWidgetGenerated}
          />
        </div>

        {/* Dynamic Display Panel */}
        <div className="flex-1 h-full bg-[#0a0f1d] border border-[#1e293b] rounded-xl overflow-hidden flex flex-col shadow-2xl">
          {/* Tab Selection */}
          <div className="bg-[#0e1628] border-b border-[#1e293b] flex justify-between items-center px-4">
            <div className="flex space-x-1">
              <button
                onClick={() => setActiveResultTab('plan')}
                className={`px-4 py-3.5 text-xs font-semibold border-b-2 transition-all flex items-center space-x-1.5 ${
                  activeResultTab === 'plan'
                    ? 'border-sky-500 text-sky-400 bg-sky-500/5'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Terminal className="h-4 w-4" />
                <span>Query Plan & SQL</span>
              </button>
              <button
                onClick={() => setActiveResultTab('dashboard')}
                className={`px-4 py-3.5 text-xs font-semibold border-b-2 transition-all flex items-center space-x-1.5 ${
                  activeResultTab === 'dashboard'
                    ? 'border-sky-500 text-sky-400 bg-sky-500/5'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Layout className="h-4 w-4" />
                <span>AI Dashboard</span>
              </button>
              <button
                onClick={() => setActiveResultTab('workflow')}
                className={`px-4 py-3.5 text-xs font-semibold border-b-2 transition-all flex items-center space-x-1.5 ${
                  activeResultTab === 'workflow'
                    ? 'border-sky-500 text-sky-400 bg-sky-500/5'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Compass className="h-4 w-4" />
                <span>AI Workflow</span>
              </button>
            </div>
            
            {activeResultTab === 'workflow' && activeWorkflow && (
              <button
                onClick={handleSaveWorkflow}
                className="px-3 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold flex items-center space-x-1"
              >
                <CheckSquare className="h-3.5 w-3.5" />
                <span>Deploy Workflow</span>
              </button>
            )}
          </div>

          {/* Tab Contents */}
          <div className="flex-1 overflow-hidden p-6">
            {activeResultTab === 'plan' && (
              <div className="h-full flex flex-col space-y-4 overflow-y-auto">
                {activeQueryPlan ? (
                  <>
                    <div className="bg-[#101827] border border-[#243553] p-4 rounded-xl space-y-2">
                      <div className="flex items-center space-x-2 text-sky-400 font-bold text-xs uppercase tracking-wider">
                        <Sparkles className="h-4 w-4 text-amber-400" />
                        <span>Federated Query Explanation</span>
                      </div>
                      <p className="text-xs text-slate-300 leading-relaxed">{activeQueryPlan.explanation}</p>
                    </div>

                    <div className="bg-[#0b101c] border border-[#223354] p-4 rounded-xl space-y-3">
                      <div className="text-slate-400 font-bold text-xs uppercase tracking-wider">Plan Execution Trace</div>
                      <div className="space-y-3">
                        {activeQueryPlan.plan_steps.map((step: any) => (
                          <div key={step.step} className="flex items-start space-x-3 bg-[#11192a] p-3 rounded-lg border border-[#22314a]">
                            <div className="bg-sky-500/10 text-sky-400 border border-sky-500/30 w-6 h-6 rounded-full flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                              {step.step}
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="flex justify-between items-center">
                                <span className="text-xs font-bold text-white uppercase">{step.service} Service</span>
                                <span className="bg-slate-800 text-[10px] text-slate-400 px-2 py-0.5 rounded font-mono font-semibold">{step.action}</span>
                              </div>
                              <code className="block text-[10px] text-slate-400 mt-2 truncate bg-[#070b13] p-1.5 rounded border border-[#1b263b] font-mono">
                                {JSON.stringify(step.parameters)}
                              </code>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {activeQueryPlan.generated_sql && (
                      <div className="bg-[#090d16] border border-[#1b263b] p-4 rounded-xl space-y-2 flex flex-col">
                        <div className="text-slate-400 font-bold text-xs uppercase tracking-wider flex justify-between items-center">
                          <span>Generated Trino SQL</span>
                          <button
                            onClick={() => navigator.clipboard.writeText(activeQueryPlan.generated_sql)}
                            className="text-[10px] text-sky-400 hover:text-sky-300 font-semibold"
                          >
                            Copy SQL
                          </button>
                        </div>
                        <pre className="text-xs bg-[#05080e] text-blue-300 p-3 rounded-lg font-mono border border-slate-900 overflow-x-auto select-all leading-normal whitespace-pre-wrap">
                          {activeQueryPlan.generated_sql}
                        </pre>
                      </div>
                    )}
                  </>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 space-y-2">
                    <Terminal className="h-8 w-8 text-slate-700" />
                    <h4 className="text-xs font-bold uppercase tracking-wider">No Query Plan Compiled</h4>
                    <p className="text-xs max-w-xs">Ask the assistant to query compounds or assay results to generate federated search maps.</p>
                  </div>
                )}
              </div>
            )}

            {activeResultTab === 'dashboard' && (
              <div className="h-full flex flex-col overflow-y-auto">
                {activeDashboard ? (
                  <div className="space-y-6">
                    <div className="flex justify-between items-center">
                      <div>
                        <h3 className="text-sm font-bold text-white">{activeDashboard.title}</h3>
                        <p className="text-[10px] text-slate-400">Dynamic AI Generated Plotly Layout</p>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {activeDashboard.widgets.map((widget: any) => (
                        <div
                          key={widget.id}
                          className="bg-[#0e1628] border border-[#1e293b] p-4 rounded-xl space-y-3 shadow-md"
                        >
                          <div className="flex justify-between items-center border-b border-[#1e293b] pb-2">
                            <span className="text-xs font-bold text-white">{widget.title}</span>
                            <span className="bg-slate-800 text-[9px] text-slate-400 px-1.5 py-0.5 rounded font-mono uppercase">{widget.type}</span>
                          </div>
                          
                          <div className="w-full flex justify-center overflow-hidden">
                            <Plot
                              data={widget.plotly_data}
                              layout={{
                                ...widget.plotly_layout,
                                width: 320,
                                height: 220,
                                margin: { l: 40, r: 10, t: 30, b: 40 }
                              }}
                              config={{ displayModeBar: false }}
                            />
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 space-y-2">
                    <Layout className="h-8 w-8 text-slate-700" />
                    <h4 className="text-xs font-bold uppercase tracking-wider">No AI Dashboard Rendered</h4>
                    <p className="text-xs max-w-xs">Prompt the assistant to compile a dashboard (e.g. "show compounds target charts") to dynamically structure charts.</p>
                  </div>
                )}
              </div>
            )}

            {activeResultTab === 'workflow' && (
              <div className="h-full flex flex-col">
                {activeWorkflow ? (
                  <div className="h-full flex flex-col space-y-3">
                    <div>
                      <h3 className="text-xs font-bold text-sky-400 uppercase tracking-wider">React Flow Graph Compilation</h3>
                      <h4 className="text-sm font-bold text-white">{activeWorkflow.name}</h4>
                      <p className="text-[10px] text-slate-400">{activeWorkflow.description}</p>
                    </div>

                    <div className="flex-1 bg-[#0b101c] border border-[#223354] rounded-xl overflow-hidden relative">
                      <ReactFlow
                        nodes={activeWorkflow.flowNodes}
                        edges={activeWorkflow.flowEdges}
                        fitView
                      >
                        <Background color="#1e293b" gap={12} />
                        <Controls />
                        <MiniMap style={{ background: '#0a0f1d', border: '1px solid #1e293b' }} />
                      </ReactFlow>
                    </div>
                  </div>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 space-y-2">
                    <Compass className="h-8 w-8 text-slate-700" />
                    <h4 className="text-xs font-bold uppercase tracking-wider">No Workflow Designed</h4>
                    <p className="text-xs max-w-xs">Ask the assistant: "Create a workflow that syncs Benchling daily..." to dynamically structure a run pipeline.</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
