#!/usr/bin/env python3
"""
AnalytiX – K8s Manifest Generator
=============================================
Generates production-ready Kubernetes YAML for all 10 microservices.
Run: python generate_k8s_manifests.py

Each service gets:
  - Deployment (with liveness/readiness/startup probes, resource limits, anti-affinity)
  - Service (ClusterIP)
  - HPA (auto-scaling)
  - PodDisruptionBudget

Output: infra/k8s/services/<service-name>.yaml
"""

import os
import yaml

SERVICES = [
    {"name": "auth-service",           "port": 8001, "replicas": 2, "cpu_req": "100m", "mem_req": "128Mi", "cpu_lim": "500m",  "mem_lim": "256Mi",  "max_replicas": 6,  "tier": "security",     "pg_db": "genquantaa_auth"},
    {"name": "metadata-service",       "port": 8002, "replicas": 2, "cpu_req": "100m", "mem_req": "128Mi", "cpu_lim": "500m",  "mem_lim": "256Mi",  "max_replicas": 8,  "tier": "data",         "pg_db": "genquantaa_metadata"},
    {"name": "query-service",          "port": 8003, "replicas": 2, "cpu_req": "200m", "mem_req": "256Mi", "cpu_lim": "1000m", "mem_lim": "512Mi",  "max_replicas": 10, "tier": "data",         "pg_db": "genquantaa_query"},
    {"name": "cheminformatics-service","port": 8004, "replicas": 2, "cpu_req": "500m", "mem_req": "512Mi", "cpu_lim": "2000m", "mem_lim": "2048Mi", "max_replicas": 6,  "tier": "science",      "pg_db": "cheminformatics", "pg_host": "postgres-rdkit"},
    {"name": "connector-service",      "port": 8005, "replicas": 2, "cpu_req": "100m", "mem_req": "128Mi", "cpu_lim": "500m",  "mem_lim": "256Mi",  "max_replicas": 6,  "tier": "integration",  "pg_db": "genquantaa_connector"},
    {"name": "audit-service",          "port": 8006, "replicas": 2, "cpu_req": "100m", "mem_req": "128Mi", "cpu_lim": "300m",  "mem_lim": "256Mi",  "max_replicas": 4,  "tier": "compliance",   "pg_db": "genquantaa_audit"},
    {"name": "lineage-service",        "port": 8007, "replicas": 2, "cpu_req": "100m", "mem_req": "128Mi", "cpu_lim": "500m",  "mem_lim": "256Mi",  "max_replicas": 4,  "tier": "governance",   "pg_db": "genquantaa_lineage"},
    {"name": "bioinformatics-service", "port": 8008, "replicas": 2, "cpu_req": "500m", "mem_req": "512Mi", "cpu_lim": "2000m", "mem_lim": "2048Mi", "max_replicas": 6,  "tier": "science",      "pg_db": "genquantaa_bioinfo"},
    {"name": "workflow-service",       "port": 8009, "replicas": 2, "cpu_req": "200m", "mem_req": "256Mi", "cpu_lim": "1000m", "mem_lim": "512Mi",  "max_replicas": 8,  "tier": "automation",   "pg_db": "genquantaa_workflow"},
    {"name": "ai-service",             "port": 8010, "replicas": 1, "cpu_req": "500m", "mem_req": "1024Mi","cpu_lim": "2000m", "mem_lim": "4096Mi", "max_replicas": 4,  "tier": "intelligence", "pg_db": "genquantaa_ai"},
]

SECRET_ENV = {
    "auth-service":      [{"name": "SECRET_KEY", "secret_key": "auth-secret-key"},
                          {"name": "AUDIT_API_SECRET", "secret_key": "auth-audit-secret"}],
    "connector-service": [{"name": "ENCRYPTION_KEY", "secret_key": "connector-encryption-key"}],
    "audit-service":     [{"name": "AUDIT_API_SECRET", "secret_key": "auth-audit-secret"}],
}

def make_manifest(svc: dict) -> str:
    name = svc["name"]
    port = svc["port"]
    replicas = svc["replicas"]
    max_replicas = svc["max_replicas"]
    tier = svc["tier"]
    image = f"discover-{name}:latest"
    pg_db = svc.get("pg_db", name.replace("-service", ""))
    pg_host = svc.get("pg_host", "postgres")


    # Extra secret env vars
    extra_env = []
    for sec in SECRET_ENV.get(name, []):
        extra_env.append({
            "name": sec["name"],
            "valueFrom": {"secretKeyRef": {"name": "genquantaa-secrets", "key": sec["secret_key"]}}
        })

    manifest = f"""# Auto-generated by generate_k8s_manifests.py
# Service: {name} | Port: {port} | Tier: {tier}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: genquantaa
  labels:
    app: {name}
    tier: {tier}
    app.kubernetes.io/part-of: genquantaa-helix
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{port}"
    prometheus.io/path: "/metrics"
spec:
  replicas: {replicas}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
        tier: {tier}
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {name}
          image: {image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {port}
              name: http
          env:
            - name: PORT
              value: "{port}"
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: genquantaa-config
                  key: ENVIRONMENT
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: genquantaa-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@{pg_host}:5432/{pg_db}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genquantaa-db-credentials
                  key: postgres-password
"""
    for env in extra_env:
        manifest += f"""            - name: {env['name']}
              valueFrom:
                secretKeyRef:
                  name: {env['valueFrom']['secretKeyRef']['name']}
                  key: {env['valueFrom']['secretKeyRef']['key']}
"""

    manifest += f"""          resources:
            requests:
              cpu: "{svc['cpu_req']}"
              memory: "{svc['mem_req']}"
            limits:
              cpu: "{svc['cpu_lim']}"
              memory: "{svc['mem_lim']}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {port}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: {port}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: {port}
            failureThreshold: 30
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: [{name}]
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: genquantaa
  labels:
    app: {name}
spec:
  selector:
    app: {name}
  ports:
    - name: http
      protocol: TCP
      port: {port}
      targetPort: {port}
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {name}-hpa
  namespace: genquantaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {name}
  minReplicas: {replicas}
  maxReplicas: {max_replicas}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {name}-pdb
  namespace: genquantaa
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {name}
"""
    return manifest


if __name__ == "__main__":
    output_dir = os.path.join(os.path.dirname(__file__), "services")
    os.makedirs(output_dir, exist_ok=True)
    for svc in SERVICES:
        fname = os.path.join(output_dir, f"{svc['name']}.yaml")
        content = make_manifest(svc)
        with open(fname, "w") as f:
            f.write(content)
        print(f"[OK] Generated: {fname}")
    print(f"\n[DONE] All {len(SERVICES)} service manifests generated.")
